# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "libvirt" do |libvirt, override|
    libvirt.memory = 1024
  end

  ## !!! Warning - virtualbox provider has not been tested !!!
  config.vm.provider "virtualbox" do |vbox, override|
    vbox.memory = 1024
    vbox.cpus = 2
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = "/vagrant/playbook.yml"
    ansible.sudo = true
  end
end
